export const skillsList = [
    "Semantic & accessible HTML",
    "JavaScript (ES6+)",
    "Immutability",
    "CSS BEM convention",
    "CSS Flexbox",
    "CSS Grid",
    "React",
    "React Hooks",
    "React Router",
    "Redux (Toolkit)",
    "Redux-Saga",
    "Promises, Async/Await",
    "Working with API (fetch, axios)",
    "Error handling",
    "NPM",
    "Markdown",
    "Git",
    "GitHub Pull Requests & Reviews",
    "Teamwork",
    "Scrum",
    "Trello",
    "Responsive Web Design",
    "Java (Basic knowledge)",
    "Matlab (Basic knowledge)",
    "Android Studio",
    "Firebase",
  ];

  export const toLearnList = [
      "TypeScript",
      "React Native",
      "Wordpress",
      "C++",
      "VST Programming",
  ];